[project]
name = "aind-experiment-vr-foraging-fip"
version = "0.3.0"
description = "A thin wrapper that runs VrForaging + FIP experiments"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aind-behavior-vr-foraging[data, mappers]",
    "aind-behavior-vr-foraging-curricula",
    "aind-physiology-fip",
    "aind-clabe>=0.11.0",
    "ruff"
]


[tool.uv.sources]
aind-behavior-vr-foraging = { path = "./Aind.Behavior.VrForaging/src/packages/aind_behavior_vr_foraging", editable = true }
aind-behavior-vr-foraging-curricula = { path = "./Aind.Behavior.VrForaging/src/packages/aind_behavior_vr_foraging_curricula", editable = true }
aind-physiology-fip = { path = "./Aind.Physiology.Fip", editable = true }